package com.ordwen.odailyquests.quests;

public enum ConditionType {

    EQUALS,
    NOT_EQUALS,
    GREATER_THAN,
    LESS_THAN,
    GREATER_THAN_OR_EQUALS,
    LESS_THAN_OR_EQUALS,

    DURATION_GREATER_THAN,
    DURATION_LESS_THAN,
    DURATION_GREATER_THAN_OR_EQUALS,
    DURATION_LESS_THAN_OR_EQUALS,
}
