name: Generate and Deploy Javadoc

on:
  push:
    branches:
      - 3.0.0
    paths:
      - 'src/**'
      - 'build.gradle'
      - 'settings.gradle'
      - '.github/workflows/deploy-javadoc.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Make Gradle Wrapper executable
        run: chmod +x ./gradlew

      - name: Generate Javadoc
        run: ./gradlew javadoc

      - name: Install SSH client
        run: sudo apt-get install -y openssh-client

      - name: Deploy Javadoc via rsync over SSH
        env:
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_HOST: ${{ secrets.FTP_HOST }}
          FTP_TARGET_PATH: ${{ secrets.FTP_TARGET_PATH }}
          FTP_PORT: ${{ secrets.FTP_PORT }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        run: |
          sudo apt-get update && sudo apt-get install -y rsync sshpass

          mkdir -p ~/.ssh
          echo "StrictHostKeyChecking no" >> ~/.ssh/config

          sshpass -p "$FTP_PASSWORD" rsync -avz -e "ssh -p $FTP_PORT -o StrictHostKeyChecking=no" \
            build/docs/javadoc/ \
            $FTP_USERNAME@$FTP_HOST:$FTP_TARGET_PATH