name: Snapshots

on:
  push:
    branches:
      - '3.0.0'
  workflow_dispatch:

env:
  SNAPSHOT_BRANCH: 3.0.0
  JAVA_VERSION: '21'

jobs:
  build-snapshot:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}

      - name: Compute meta (version & sha)
        id: meta
        run: |
          SHA=$(git rev-parse --short HEAD)
          echo "sha=$SHA" >> $GITHUB_OUTPUT
          echo "version=3.0.0-SNAPSHOT+$SHA" >> $GITHUB_OUTPUT

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build (snapshot, shadowJar)
        run: ./gradlew clean shadowJar -x test
        env:
          ORG_GRADLE_PROJECT_version: ${{ steps.meta.outputs.version }}

      - name: List built artifacts (debug)
        run: |
          echo "=== */build/libs contents ==="
          find . -type f -path "*/build/libs/*" -maxdepth 1 -print | sed 's#^# -> #'
          echo "================================"

      - name: Collect JAR files
        id: collect
        run: |
          FILES=$(find . -type f -path "*/build/libs/*.jar" \
            ! -name "*-sources.jar" ! -name "*-javadoc.jar" -print | tr '\n' ' ')
          if [ -z "$FILES" ]; then
            echo "No JARs found under */build/libs/*.jar"
            exit 1
          fi
          echo "files=$FILES" >> $GITHUB_OUTPUT
          echo "Will upload: $FILES"

      - name: Delete previous JAR assets on prerelease
        uses: actions/github-script@v7
        env:
          TAG: nightly-${{ env.SNAPSHOT_BRANCH }}
        with:
          script: |
            const tag = process.env.TAG;
            const { owner, repo } = context.repo;
            let release;
            try {
              release = await github.rest.repos.getReleaseByTag({ owner, repo, tag });
            } catch (e) {
              core.info(`No release found for tag ${tag} (first run?). Nothing to delete.`);
              return;
            }
            for (const asset of release.data.assets) {
              if (asset.name.endsWith('.jar')) {
                core.info(`Deleting asset: ${asset.name} (${asset.id})`);
                await github.rest.repos.deleteReleaseAsset({ owner, repo, asset_id: asset.id });
              }
            }

      - name: Create/Update prerelease (nightly)
        uses: softprops/action-gh-release@v2
        with:
          tag_name: nightly-${{ env.SNAPSHOT_BRANCH }}
          name: "Nightly ${{ env.SNAPSHOT_BRANCH }}"
          body: |
            ⚠️ Development snapshot (unsupported)
            Commit: ${{ github.sha }}
            Version: ${{ steps.meta.outputs.version }}
          draft: false
          prerelease: true
          files: ${{ steps.collect.outputs.files }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build mini changelog (last 10 commits)
        id: changelog
        run: |
          echo "changes<<EOF" >> $GITHUB_OUTPUT
          git log -n 10 --pretty=format:'- %h %s' >> $GITHUB_OUTPUT
          echo "" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Compute public release URL
        id: relurl
        run: |
          echo "url=https://github.com/${GITHUB_REPOSITORY}/releases/tag/nightly-${{ env.SNAPSHOT_BRANCH }}" >> $GITHUB_OUTPUT

      - name: Post Discord embed
        env:
          WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
          VERSION: ${{ steps.meta.outputs.version }}
          SHA: ${{ steps.meta.outputs.sha }}
          URL: ${{ steps.relurl.outputs.url }}
          CHANGES: ${{ steps.changelog.outputs.changes }}
        run: |
          if [ -z "$WEBHOOK" ]; then
            echo "No webhook configured, skipping Discord notification."
            exit 0
          fi

          DESC="$(printf '%s\n\n**Download & notes:** %s' "$CHANGES" "$URL")"
          DESC="${DESC:0:1900}"

          curl -X POST -H "Content-Type: application/json" -d "$(jq -nc --arg v "$VERSION" --arg s "$SHA" --arg d "$DESC" --arg u "$URL" \
          '{embeds: [{title: ("ODailyQuests Snapshot " + $v), url: $u, description: $d, color: 16753920, footer: {text: ("Commit " + $s)}}]}')" "$WEBHOOK"
